### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by EliseLavielle** [quentin-sommer/strasbourg-loyer-front#1]
I think you should update the readme of this wonderful project of yours !

**Comment by quentin-sommer** [comment]
I guess I should yep. I'll push a nice json file as well for the non-js guys to be able to consume the data

**Comment by quentin-sommer** [comment]
Fixed in https://github.com/quentin-sommer/strasbourg-loyer-front/commit/673ae7413809b11ea8ac1138dc8c90639c274ffe
